<?php

/**
 * MasaDB install program
 */

// phpinfo();exit;

session_start();

require __DIR__ . "/vendor/autoload.php";

use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\Local;
use \Git\Coyl\Git;

if( isset($_POST) && !empty($_POST) ){ // post

	$post_data = $_POST;


	$config_data = json_encode($post_data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
	// echo "<pre>";var_dump(json_encode($config_data));exit;

	// create the config file ------------ 1
	$adapter = new Local(__DIR__);
	$filesystem = new Filesystem($adapter);

	if( $filesystem->has('config.json') ){
		$filesystem->delete('config.json');
	}
	if( !$filesystem->write('config.json', $config_data) ){
		exit("Error: Problem writing config file!");
	}
	// --


	// create database data address ------------ 2
	$adapter_data = new Local("/");
	$filesystem_data = new Filesystem($adapter_data);

	if( $filesystem_data->has($post_data['database-address']) ){
		exit("Error: Directory for data already exists!");
	}

	if( !$filesystem_data->createDir($post_data['database-address']) ){
		exit("Error: Problem creating 'database-address'!");
	}
	// --


	// turn the data directory into git repository ------------ 3
	\Coyl\Git\Git::create($post_data['database-address']);
	// --


	// add oauth databases to data directoey ------------ 4
	// --


	// header("Location: index.php");
	exit("End of Post part.");

}else{ // form

	?>
	<style type="text/css">
		label{
			font-weight: bold;
		}

		code{
			display: block;
			padding: 3px 5px;
			border: 1px solid #000;
			background-color: #ccc;
			border-radius: 4px;
			margin-top: 5px;
			margin-bottom: 5px;
		}

		input{
			width: 100%;
		}

		.row{
			margin-bottom: 15px;
		}
	</style>

	<form action="install.php" method="POST">

		<div><h1>1 Step</h1></div>

		<div class="row">
			<div><label>Database Address:</label></div>
			<div><input type="text" name="database-address" value="<?php echo __DIR__; ?>/data" /></div>
			<div>Obs.: must be a place where www-data user has access.</div>
		</div>

		<div class="row">
			<div><label>Database Domain:</label></div>
			<div><input type="text" name="domain" value="db.masa.tech" /></div>
		</div>

		<div class="row">
			<div><label>Display Errors:</label></div>
			</div><input type="text" name="displayErrorDetails" value="true"/></div>
		</div>

		<div class="row">
			<div><label>Private Key Address:</label></div>
			<div><input type="text" name="private_key" value="<?php echo __DIR__ ?>/masadb.key" /></div>
			<div>
				Obs.: can be generated by: 
				<code>ssh-keygen -t rsa -b 4096</code>
				<code>openssl req -new -newkey rsa:2048 -nodes -keyout masadb.key -out masadb.csr</code>
				<code>openssl rsa -in masadb.key -pubout > masadb.pub</code>
			</div>
		</div>

		<div class="row">
			<div><label>Public Key Address:</label></div>
			<div><input type="text" name="public_key" value="<?php echo __DIR__ ?>/masadb.key"/></div>
		</div>

		<div class="row">
			<div>&nbsp;</div>
			<div><input type="submit" value="Next" /></div>
		</div>

	</form>
	<?php 

}

exit("---");